export const PARTNER_ACTIONS = {
  GET_PARTNER_INFORMATION: "GET_PARTNER_INFORMATION",
  SET_PARTNER: "SET_PARTNER",
};

export const ORDER_ACTIONS = {
  CREATE_ORDER: "CREATE_ORDER",
  CANCEL_ORDER: "CANCEL_ORDER",
  RESET_ORDER: "RESET_ORDER",

  GET_ORDER: "GET_ORDER",
  GET_HISTORY: "GET_HISTORY",
};

export const STORE_ACTIONS = {
  SET_SUGGESTION_STORES: "SET_SUGGESTION_STORE",
};

export const MAP_ACTIONS = {
  SET_ADDRESS: "SET_ADDRESS",
};
