export const PARTNER_ACTIONS = {
  GET_PARTNER_INFORMATION: "GET_PARTNER_INFORMATION",
  SET_PARTNER: "SET_PARTNER",
};

export const ORDER_ACTIONS = {
  CREATE_ORDER: "CREATE_ORDER",
  CANCEL_ORDER: "CANCEL_ORDER",
  RESET_ORDER: "RESET_ORDER",
  SET_CREATED_ORDER: "SET_CREATED_ORDER",

  GET_ORDER: "GET_ORDER",
  GET_HISTORY: "GET_HISTORY",
};

export const EMERGENCY_ACTION = {
  GET_ORDER: "GET_ORDER",
  GET_EMERGENCY: "GET_EMERGENCY",
  CREATE_EMERGENCY: "CREATE_EMERGENCY",
  EDIT_EMERGENCY: "EDIT_EMERGENCY",
  GET_HISTORY: "GET_HISTORY",
  GET_PARTNER: "GET_PARTNER",
  GET_DESTINATION: "GET_DESTINATION",
  STORE_ORDER: "STORE_ORDER",
  STORE_SCHEDULE: "STORE_SCHEDULE",
};

export const STORE_ACTIONS = {
  SET_SUGGESTION_STORES: "SET_SUGGESTION_STORE",
};

export const MAP_ACTIONS = {
  SET_ADDRESS: "SET_ADDRESS",
};

export const ACCOUNT_ACTION = {
  RESET_CUSTOMER: "RESET_CUSTOMER",
};
